websites:
  URL: http://www.baidu.com

log:
  file_name: testFramework.log
  backup: 5
  console_level: WARNING
  file_level: DEBUG
  pattern: '%(asctime)s - %(name)s - %(module)s - %(funcName)s - %(levelname)s - %(message)s'

email:
  smtpserver: smtp.qq.com
  sender: ricky2971@qq.com
  password: 1111111111111111
