websites:
  URL: http://www.baidu.com

log:
  file_name: test.log
  backup: 5
  console_level: WARNING
  file_level: DEBUG
  pattern: '%(asctime)s - %(name)s - %(module)s - %(funcName)s - %(levelname)s - %(message)s'